apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80                   # Port that the service will expose
      targetPort: 80              #Port on the container that the service will forward to
      nodePort: 30007             # Port on each node where the service will be exposed
